apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollin-auth-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: kiran6177/rollin-auth
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: CLIENT_SECRET
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: EMAIL
        - name: JWT_AUTHSECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_AUTHSECRET
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: JWT_REFRESH_SECRET
        - name: MONGOURL
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: MONGOURL
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: PASSWORD
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: PORT
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: S3_ACCESS_KEY
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: S3_BUCKET_NAME
        - name: S3_BUCKET_REGION
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: S3_BUCKET_REGION
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: S3_SECRET_ACCESS_KEY
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: SESSION_SECRET
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: TWILIO_ACCOUNT_SID
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: TWILIO_AUTH_TOKEN
        - name: TWILIO_MESSAGE_SID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: TWILIO_MESSAGE_SID
        - name: TWILIO_VERIFY_SID
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: TWILIO_VERIFY_SID
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
  - name: auth
    protocol: TCP
    port: 4001
    targetPort: 4001

